DwhSchemaUpdaterJob:
  Db:
    LogsConnString:
      settings-key: DwhSchemaUpdaterJob-LogsConnString
      types:
        - AzureTableStorage
    SqlConnString:
      settings-key: DwhSchemaUpdaterJob-SqlConnString
  DwhBlobAccountName:
      settings-key: DwhSchemaUpdaterJob-DwhBlobAccountName
  DwhBlobAccountKey:
      settings-key: DwhSchemaUpdaterJob-DwhBlobAccountKey
  ForcedUpdate:
      settings-key: DwhSchemaUpdaterJob-ForcedUpdate
      types: 
        - Optional
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

